### ISSUE TITLE
CODEOWNERS file contains errors

### ISSUE THREAD

**Issue by hdamker** [camaraproject/NetworkAccessManagement#2]
**Problem description**

The CODEOWNERS file is currently not valid.

**Expected action**

@mayur007 accepts the invitation from GitHub to get a member of the camaraproject organization (and with that a member of @camaraproject/network-access-management_codeowners). 

**Additional context**

This issue can be closed as soon as GitHub shows that https://github.com/camaraproject/NetworkAccessManagement/blob/main/CODEOWNERS is valid.

**Comment by caubut-charter** [comment]
CODEOWNERS is now valid.
